filebeat.prospectors:
- type: log
  enabled: true
  fields_under_root: true
  paths:
    - /var/log/haproxy/haproxy.log
  fields:
    infralogtype: haproxy

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

name: "@@HOSTNAME@@"
fields_under_root: true
fields:
  attackscenario: @@ATTACKSCENARIO@@

output.kafka:
  hosts:  ["@@HOSTANDPORT@@"]
  topic: 'haproxy'