filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: haproxy
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

name: ${RIRHOSTNAME:haproxyhost}
fields_under_root: true
fields:
  attackscenario: ${ATTCKSCENARIO:example_scenario}

output.kafka:
  hosts:  ${KAFKAHOSTS}
  topic: 'haproxy'