- name: Copy Docker elkserver project to target server
  copy: 
    src: ../dist/elkserver/
    dest: "{{ elkserver_dir }}"

- name: Set sysctl map count for Elasticsearch
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes