version: '2'
services:
  haproxy:
    image: haproxy:latest
    environment:
      PROXYIP: ""
      PROXYPORT: 8080
    ports:
      - "80:80"
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.0
    environment:
      RIRHOSTNAME: "haproxyhost"
      KAFKAHOSTS: "localhost:9200"
      ATTCKSCENARIO: "example_scenario"
    volumes:
      - "proxylogs:/var/log/haproxy"

volumes:
  proxylogs: