version: '2'
services:
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.0
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/opt/cobaltstrike/cobaltstrike/logs:/root/cobaltstrike/logs"
    environment:
      CSHOSTNAME: "csteamserver"
      KAFKAHOSTS: "localhost:9200"
      ATTCKSCENARIO: "example_scenario"
