version: '2'
services:
  teamserver:
    build: ./cobaltstrike
    environment:
      - TS_IP: "127.0.0.1"
      - TS_PASSWORD: ""
    volumes:
      - "<path_to_cobaltstrike>:/opt/cobaltstrike"

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.0
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/opt/cobaltstrike/cobaltstrike/logs:/root/cobaltstrike/logs"
    environment:
      CSHOSTNAME: "csteamserver"
      KAFKAHOSTS: "localhost:9200"
      ATTCKSCENARIO: "example_scenario"
