- name: Copy Docker relay project to target server
  copy: 
    src: ../dist/redirs/
    dest: "{{ redirs_dir }}/"

- name: Run HAProxy container
  docker_container:
    name: haproxy
    image: haproxy:latest
    recreate: yes
    env:
      LISTEN_ON_PORT: "{{ relay_settings.listen_on_port }}"
      FORWARD_TO_IP: "{{ relay_settings.forward_to_ip }}"
      FORWARD_TO_PORT: "{{ relay_settings.forward_to_port }}"
    ports:
      - "{{ relay_settings.listen_on_port}}:{{ relay_settings.listen_on_port }}"
    volumes:
      - "{{ redirs_dir }}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"

- name: Run Filebeat container
  docker_container:
    name: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.0
    recreate: yes
    user: root
    env:
      RIRHOSTNAME: "haproxyhost"
      KAFKAHOSTS: "{{ kafka_host }}"
      ATTCKSCENARIO: "{{ campaign_name }}"
    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ redirs_dir }}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"

