version: '3'
services:
  redis_service:
    image: redis
                                                                                        
  zookeeper:                                                                                       
     image: confluentinc/cp-zookeeper:latest                                                      
     environment:                                                                                 
        ZOOKEEPER_CLIENT_PORT: 2181                                                                                
                                                                                                  
  kafka:                                                                                           
    image: confluentinc/cp-kafka:latest                                                            
    environment:                                                                                   
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"                                                                                         

  # Change the following systemconfig to enable higher memory mapping
  # sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    restart: unless-stopped
    environment:
      - cluster.name=redelk-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata_node1:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    restart: unless-stopped
    links:
      - elasticsearch
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    links:
      - elasticsearch
      - kafka
    volumes:
      - "./logstash/conf.d:/usr/share/logstash/pipeline"
      - "./logstash/geoip:/usr/share/logstash/GeoLite2-dbs"

  alerting:
    image: bitsensor/elastalert:latest
    links:
      - elasticsearch
    volumes:
      - "./alerting/config/config.yaml:/opt/elastalert/config.yaml"
      - "./alerting/config/config.json:/opt/elastalert-server/config/config.json"
      - "./alerting/rules:/opt/elastalert/rules"
      - "./alerting/templates:/opt/elastalert/rule_templates"

  elkworker:
    build: ./worker
    links:
      - elasticsearch
    volumes:
      - "./etc:/etc/redelk"

volumes:
  esdata_node1:
    driver: local