version: '3'
services:
  redis_service:
    image: redis

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_BYTES: 1000000000
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  # Change the following systemconfig to enable higher memory mapping
  # sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    restart: unless-stopped
    environment:
      - cluster.name=redelk-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata_node1:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    restart: unless-stopped
    links:
      - elasticsearch
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    links:
      - elasticsearch
      - kafka
    volumes:
      - "./logstash/conf.d:/usr/share/logstash/pipeline"

  alerting:
    image: bitsensor/elastalert:latest
    links:
      - elasticsearch
    volumes:
      - "./alerting/config/config.yaml:/opt/elastalert/config.yaml"
      - "./alerting/config/config.json:/opt/elastalert-server/config/config.json"
      - "./alerting/rules:/opt/elastalert/rules"
      - "./alerting/templates:/opt/elastalert/rule_templates"

  elkworker:
    build: ./worker
    links:
      - elasticsearch
    volumes:
      - "./etc:/etc/redelk"

volumes:
  esdata_node1:
    driver: local