

- name: Installing python passlib for nginx htpasswd management
  pip:
    name: "passlib"
    state: present


- name: Copy NGINX config template
  template:
    src: proxy.conf.j2
    dest: "{{ elkserver_dir }}/nginx/conf/proxy.conf"

- name: Creating htaccess for NGINX container
  htpasswd:
    state: present
    create: yes
    name: "{{ nginx_username }}"
    password: "{{ nginx_password }}"
    path: "{{ elkserver_dir }}/nginx/conf/.htpasswd"
    mode: 0644

- name: Run NGINX container
  docker_container:
    name: nginx
    image: nginx
    state: started
    recreate: yes
    networks:
      - name: analytics_network
        aliases:
          - nginx
        links:
          - kibana
    volumes:
      - "{{ elkserver_dir }}/nginx/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf"
      - "{{ elkserver_dir }}/nginx/conf/.htpasswd:/etc/nginx/.htpasswd"
      - "filesyncdata:/var/www/html/cslogs"
    ports:
      - "80:80"

