- hosts: all
  become: yes
  strategy: free
  roles:
    - { role: generic, tags: ['generic', 'core'] }
    - { role: firewall, tags: ['firewall', 'core'] }
    - { role: docker, tags: ['docker', 'core'] }

- hosts: relay
  become: yes
  roles:
    - { role: relay, tags: ['relay'], when: "'relay' in group_names" }


- hosts: analytics
  become: yes
  vars_prompt:
    - name: "nginx_username"
      prompt: "Username for NGINX htpasswd?"
    - name: "nginx_password"
      prompt: "Password for NGINX htpasswd?"
  roles:
    - { role: analytics, tags: ['elkserver', 'analytics'], when: "'analytics' in group_names" }
    - { role: filesync, tags: ['filesync', 'analytics'], when: "'analytics' in group_names" }
    - { role: nginx, tags: ['nginx', 'analytics'], when: "'analytics' in group_names" }
    - { role: elkstack, tags: ['elkstack', 'analytics'], when: "'analytics' in group_names" }
    - { role: intel, tags: ['intel', 'analytics'], when: "'analytics' in group_names" }
    - { role: enricher, tags: ['enricher', 'analytics'], when: "'analytics' in group_names" }


- hosts: backendc
  become: yes
  roles:
    - { role: teamserver, tags: ['teamserver'], when: "'backend' in group_names" }
