# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: /elastalert/rules

run_every:
  minutes: 1

buffer_time:
  minutes: 15

es_host: elasticsearch
es_port: 9200

writeback_index: elastalert_status

alert_time_limit:
  days: 2
